resources:
  - name: mount_volumes_repo
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration  
      path: manishas-jfrog/example-mount-volumes    # replace with your repository name
      branches:
        include: master
        
pipelines:
  - name: mount_volumes_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          affinityGroup: mountedVolumes
          runtime:           
            type: image
            image:
              custom:
                name: docker.bintray.io/jfrog/pipelines-u16node
                tag: "10.18.0"
                options: "-v /tmp/shared:/tmp/shared -v /tmp/myFolder:/tmp/myFolder"             
          inputResources:
            - name: mount_volumes_repo
        execution:
          onExecute:
            - cd /tmp/shared
            - echo 'Hello World in shared' > file_shared.txt
            - cd /tmp/myFolder
            - echo 'Hello World in myFolder' > file_myFolder.txt
            
      - name: step_2
        type: Bash
        configuration:
          affinityGroup: mountedVolumes 
          runtime:           
            type: image
            image:
              custom:
                name: docker.bintray.io/jfrog/pipelines-u16node
                tag: "10.18.0"
                options: "-v /tmp/shared:/tmp/shared -v /tmp/myFolder:/tmp/myFolder"                
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - cd /tmp/shared
            - cat file_shared.txt 
            - cd /tmp/myFolder
            - cat file_myFolder.txt
